export * from './shared/apiClient';
export * from './shared/domainRegistry';
export * as CommerceDomain from './commerce';
export * as PaymentDomain from './payment';
export * as ChatDomain from './chat';
export * as LogisticsDomain from './logistics';
export * as IdentityDomain from './identity';
export * as MediaDomain from './media';
export * as AiDomain from './ai';
export * as ImpactDomain from './impact';
export * as FreelanceDomain from './freelance';
export * as BusinessDomain from './business';
export * as EducationDomain from './education';
export * as HealthDomain from './health';
